name: linter-check

on: push

jobs:
  makeLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js dependencies
        run: make install

      - name: Start linter
        run: make lint
